Sprint 10
DmitryRedka/ImageFeed pull request #5
Opened 2023-03-04 04:29 UTC by DmitryRedka

2023-03-04 19:09 UTC, protos17 requested changes

2023-03-04 19:09 UTC, protos17 commented on Image Feed/Auth/SplashViewController.swift
> +            fatalError("Invalid to switch TapBarController")
По своему опыту хотел бы отметить, что в продакшене не используют fatalError, советую заменить на assertionFailure.

2023-03-04 19:09 UTC, protos17 commented on Image Feed/Auth/SplashViewController.swift
> +                fatalError(("Failed to prepare \(showAuthentificationScreenSegueIdentification)"))
По своему опыту хотел бы отметить, что в продакшене не используют fatalError, советую заменить на assertionFailure.

2023-03-04 19:09 UTC, protos17 commented on Image Feed/Auth/AuthViewController.swift
> +
Рекомендую убрать лишние отступы

2023-03-04 19:09 UTC, protos17 commented on Image Feed/Auth/OAuth2Service.swift
> +
Лишние отступы рекомендую убрать

2023-03-04 19:09 UTC, protos17 commented on Image Feed/Auth/OAuth2TokenStorage.swift
> +class OAuth2TokenStorage {
Давай проставлять ключевое слово `final` классам для ускорения работы компилятора.
Это нужно для оптимизация работы компилятора: ты явно сообщаешь о том, 
что класс не планируется расширять наследованием. 
В таком случае компилятор будет быстрее находить адрес ячейки памяти при вызове функции.

2023-03-04 19:09 UTC, protos17 commented on Image Feed/Auth/SplashViewController.swift
> +class SplashViewController: UIViewController {
Давай проставлять ключевое слово `final` классам для ускорения работы компилятора.
Это нужно для оптимизация работы компилятора: ты явно сообщаешь о том, 
что класс не планируется расширять наследованием. 
В таком случае компилятор будет быстрее находить адрес ячейки памяти при вызове функции.

2023-03-04 19:09 UTC, protos17 commented on Image Feed/Auth/SplashViewController.swift
> +            }
Если нужен только один случай из switch, то можно писать так:
if case .success = result {
self.switchTapBarController()
}

2023-03-04 19:09 UTC, protos17 commented on Image Feed/Auth/WebViewController.swift
> +}
Лишний, пустой класс, можно удалить

2023-03-04 19:09 UTC, protos17 commented on Image Feed/Auth/WebViewViewController.swift
> +fileprivate let UnsplashAuthorizeURLString = "https://unsplash.com/oauth/authorize"
Константы принято называть с маленькой буквы, рекомендую его также вынести в файл Constants

2023-03-04 19:09 UTC, protos17 commented on Image Feed/Auth/WebViewViewController.swift
> +    @IBAction func didTapBackButton(_ sender: Any) {
Здесь стоит добавить `private`
Необходимо указывать private  для того, чтобы спрятать детали реализации конкретной части функциональности, 
когда они используются только внутри области объявления.

2023-03-04 19:09 UTC, protos17 commented on Image Feed/ImagesList/ImagesListViewController.swift
> +
Лишний код рекомендую удалять

2023-03-04 19:09 UTC, protos17 commented on Image Feed/Resources/Constants.swift
> +let defaultBaseURL = URL(string: "https://api.unsplash.com")!
Рекомендую их вынести в класс Constants и обозначить как static let

2023-03-11 10:28 UTC, DmitryRedka commented on Image Feed/Auth/SplashViewController.swift
> +            fatalError("Invalid to switch TapBarController")
Принято

2023-03-11 10:29 UTC, DmitryRedka commented on Image Feed/Auth/SplashViewController.swift
> +                fatalError(("Failed to prepare \(showAuthentificationScreenSegueIdentification)"))
Принято

2023-03-11 10:35 UTC, DmitryRedka commented on Image Feed/Auth/WebViewViewController.swift
> +fileprivate let UnsplashAuthorizeURLString = "https://unsplash.com/oauth/authorize"
Принято

2023-03-11 10:36 UTC, DmitryRedka commented on Image Feed/Auth/WebViewViewController.swift
> +    @IBAction func didTapBackButton(_ sender: Any) {
Приянто

2023-03-11 10:54 UTC, merged

2023-03-11 20:10 UTC, protos17 commented on Image Feed/Auth/OAuth2Service.swift
> +func authTokenRequest (code: String ) -> URLRequest {
Здесь стоит добавить `private`
Необходимо указывать private  для того, чтобы спрятать детали реализации конкретной части функциональности, 
когда они используются только внутри области объявления.

2023-03-11 20:10 UTC, protos17 commented on Image Feed/Auth/OAuth2Service.swift
> +    let url = URL(string: "https://unsplash.com/oauth/token")!
Рекомендую ее вынести в Constants

2023-03-11 20:10 UTC, protos17 commented on Image Feed/Resources/Constants.swift
> +class Constants {
Рекомендую сделать его final или сделать структурой